
project_id = "qgsabaicokoynabxgdco"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
port = 54327

[auth.smtp]
sender_name = "Supabase"
sender_email = "noreply@example.com"

[analytics]
enabled = false
port = 54328

[experimental]
enabled = false

[functions]
[functions.cert-lookup]
verify_jwt = true

