
project_id = "qgsabaicokoynabxgdco"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

# Additional Edge Functions
[functions.cert-lookup]
verify_jwt = true

[functions.psa-price-lookup]
verify_jwt = true

[functions.price-scraper]
verify_jwt = true

[functions.playwright-scraper]
verify_jwt = true

