
# A string used as a secret to generate JWT tokens for functions.
# Function invocations with invalid JWT tokens are not executed.
# Set this value when deploying to production!
project_id = "qgsabaicokoynabxgdco"

# Docker image to use for local development
# docs: https://supabase.com/docs/guides/functions/local-development
[functions]
node_version = "18"

[functions.shopify-sync]
verify_jwt = true
