
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgsabaicokoynabxgdco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnc2FiYWljb2tveW5hYnhnZGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTIxNDEsImV4cCI6MjA2MDA2ODE0MX0._75NHot8gMmOcXQ88P1fqo8gyPK2FcV2g3ppmH_EFLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
